const presentationData = [
    {
        id: "015",
        emoji: "📐",
        title: "Reliability Generalization Meta-Analysis of Health Belief Model Scales: Measurement Quality, Moderators, and Implications for Statistical Power",
        authors: "Ma, H. H., Lee, B., Paek, H.-J., Kim, T., & Hong, S. W.",
        date: "2026. 5. 8.",
        conference: "Korean Society For Journalism And Communication Studies (KSJCS)",
        location: "Yeosu, Korea",
        image: "assets/presentations/images/015-image.png",
        pptLink: "assets/presentations/slides/015-slides.pdf",
        sessionPdf: "assets/presentations/sessions/015-session.pdf",
        tags: ["Meta science", "Meta analysis", "Reliability generalization", "Health communicaton"]
    },
    {
        id: "014",
        emoji: "🌐",
        title: "Exploring the Probabilistic Causal Structure of Media Trust: A Bayesian Network Analysis",
        authors: "Ma, H. H.",
        date: "2025. 5. 31.",
        conference: "Korean Association For Communication And Information Studies (KACIS)",
        location: "Busan, Korea",
        image: "assets/presentations/images/014-image.png",
        pptLink: "assets/presentations/slides/014-slides.pdf",
        sessionPdf: "assets/presentations/sessions/014-session.pdf",
        tags: ["Bayesian network", "Bayesian statistics", "Journalism"],
        award: "Outstanding Graduate Student Paper Award, Korean Association For Communication And Information Studies (KACIS), Graduate Student Division"
    },
    {
        id: "013",
        emoji: "🎰",
        title: "Designing Public Messages to Prevent Lottery Addiction: An Experiment Study to Correct Cognitive Errors",
        authors: "Ma, H. H. & Paek, H.-J.",
        date: "2024. 6. 15.",
        conference: "Korea Health Communication Association (KHCA)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/013-image.png",
        pptLink: "assets/presentations/slides/013-slides.pdf",
        sessionPdf: "assets/presentations/sessions/013-session.pdf",
        tags: ["Public communication", "Health communication", "Experiment"]
    },
    {
        id: "012",
        emoji: "🤝",
        title: "Simulated touch: A Meta-Analysis of the Effects of Virtual Social Touch on Interpersonal Communication Outcomes",
        authors: "Ma, H. H., Kim, E., Pang, S. & Lee, B.",
        date: "2024. 5. 10.",
        conference: "Korean Society For Journalism And Communication Studies (KSJCS)",
        location: "Gyeongju, Korea",
        image: "assets/presentations/images/012-image.jpeg",
        pptLink: "assets/presentations/slides/012-slides.pdf",
        sessionPdf: "assets/presentations/sessions/012-session.pdf",
        tags: ["Meta science", "Meta analysis", "Virtual reality", "Social interaction", "Bayesian statistics"]
    },
    {
        id: "011",
        emoji: "🎰",
        title: "효과적인 복권 커뮤니케이션 전략: 수용자 세분화 분석을 중심으로",
        authors: "Ma, H. H., Lee, S., & Paek, H.-J.",
        date: "2024. 4. 19.",
        conference: "Korean Academic Society For Public Relations (KASPR)",
        location: "Jeonju, Korea",
        image: "assets/presentations/images/011-image.jpeg",
        pptLink: "assets/presentations/slides/011-slides.pdf",
        sessionPdf: "assets/presentations/sessions/011-session.pdf",
        tags: ["Responsible gampling", "Public communication", "Health communication", "Audience segmentation", "Clustering"]
    },
    {
        id: "010",
        emoji: "🪴",
        title: "식품정보 리터러시가 대체식품 구매의도에 미치는 영향: 소비자의 정보추구행동과 대체식품 위험인식의 조절된 매개효과를 중심으로",
        authors: "Choi, M. Y., Ma, H. H., & Oh, H. J.",
        date: "2023. 11. 24.",
        conference: "Korean Academic Society For Public Relations (KASPR)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/010-image.jpeg",
        pptLink: "assets/presentations/slides/010-slides.pdf",
        sessionPdf: "assets/presentations/sessions/010-session.pdf",
        tags: ["Sustainability", "Public communication"]
    },
    {
        id: "009",
        emoji: "👾",
        title: "메타버스를 이용한 건강 캠페인의 효과 평가 탐색: 식중독 예방 캠페인 ‘제페토 지킬박사월드’ 사례를 중심으로",
        authors: "Ma, H. H., Choi, M. Y., Oh, J. H., & Paek, H.-J.",
        date: "2023. 6. 16.",
        conference: "Korea Health Communication Association (KHCA)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/009-image.png",
        pptLink: "assets/presentations/slides/009-slides.pdf",
        sessionPdf: "assets/presentations/sessions/009-session.pdf",
        tags: ["Virtual reality", "Campaign evaluation", "Health communication"],
        award: "Best Paper Award, Enzaim / Korea Health Communication Association"
    },
    {
        id: "008",
        emoji: "🪴",
        title: "A Preliminary Study for Developing Perceived ESG Scale to Measure Public Perception Toward Organizations’ ESG Performance",
        authors: "Oh, H. J., Park, S. J., Ma, H. H., Lee, B., & Jang, D. Y.",
        date: "2023. 5. 25.",
        conference: "ICA-KACA research session",
        location: "Toronto, Canada",
        image: "assets/presentations/images/008-image.png",
        pptLink: "assets/presentations/slides/008-slides.pdf",
        sessionPdf: "assets/presentations/sessions/008-session.pdf",
        tags: ["Scale development", "Sustainability"],
        award: "Top Paper Award, International Communication Association (ICA), Korean American Communication Association (KACA) Research Session"
    },
    {
        id: "007",
        emoji: "🗣️",
        title: "The Impact of Nonverbal Communication Cues of Avatars on Self-Disclosurein an Immersive Social VR: Focusing on Inter-Avatar Distance and Physical Attractiveness of the Interlocutor’s Avatar",
        authors: "Ma, H. H., Keum, S. Y., Pang, S., Oh, J. H., Lee, J., & Lee, B.",
        date: "2023. 5. 19.",
        conference: "Korean Society For Journalism And Communication Studies (KSJCS)",
        location: "Jeju, Korea",
        image: "assets/presentations/images/007-image.png",
        pptLink: "assets/presentations/slides/007-slides.pdf",
        sessionPdf: "assets/presentations/sessions/007-session.pdf",
        tags: ["Virtual reality", "Social interaction", "Experiment"]
    },
    {
        id: "006",
        emoji: "🗣️",
        title: "Inter-Avatar Distance and Conversation Satisfaction in Immersive VR: Exploring the Moderating Effects of the Sense of Embodiment",
        authors: "Pang, S., Ma, H. H., & Lee, B.",
        date: "2023. 5. 12.",
        conference: "Journal of Cybercommunication Academic Society (JCAS)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/006-image.png",
        pptLink: "assets/presentations/slides/006-slides.pdf",
        sessionPdf: "assets/presentations/sessions/006-session.jpg",
        tags: ["Virtual reality", "Social interaction", "Experiment"]
    },
    {
        id: "005",
        emoji: "🪴",
        title: "조직의 ESG 활동에 대한 공중 인식 평가를 위한 소셜데이터 기반 Perceived ESG Index 개발",
        authors: "Lee, B., Park, S. J., Oh, H. J., Jang, D. Y., Ma, H. H., & Cho, J. H.",
        date: "2022. 11. 25.",
        conference: "Korean Academic Society For Public Relations (KASPR)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/005-image.png",
        pptLink: "assets/presentations/slides/005-slides.pdf",
        sessionPdf: "assets/presentations/sessions/005-session.pdf",
        tags: ["Scale development", "Sustainability"]
    },
    {
        id: "004",
        emoji: "📺",
        title: "Causal impact of television anti-smoking campaign on tobacco sales in Korea: An application of bayesian structural time-series models",
        authors: "Ma, H. H. & Lee, B.",
        date: "2021. 11. 19.",
        conference: "Korea Health Communication Association (KHCA)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/004-image.png",
        pptLink: "assets/presentations/slides/004-slides.pdf",
        sessionPdf: "assets/presentations/sessions/004-session.jpg",
        tags: ["Causal inference", "Bayesian statistics", "Campaign evaluation", "Health communication"]
    },
    {
        id: "003",
        emoji: "📈",
        title: "헬스커뮤니케이션 캠페인의 인과효과 추정",
        authors: "Ma, H. H. & Lee, B.",
        date: "2021. 11. 19.",
        conference: "Korea Health Communication Association (KHCA)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/003-image.png",
        pptLink: "assets/presentations/slides/003-slides.pdf",
        sessionPdf: "assets/presentations/sessions/003-session.jpg",
        tags: ["Causal inference", "Public communication", "Campaign evaluation", "Health communication"]
    },
    {
        id: "002",
        emoji: "📈",
        title: "정부광고 인과 효과 평가 모델에 대한 탐색",
        authors: "Ma, H. H. & Lee, B.",
        date: "2021. 6. 11.",
        conference: "Korea Health Communication Association (KHCA)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/002-image.png",
        pptLink: "assets/presentations/slides/002-slides.pdf",
        sessionPdf: "assets/presentations/sessions/002-session.jpg",
        tags: ["Causal inference", "Public communication", "Campaign evaluation"]
    },
    {
        id: "001",
        emoji: "📰",
        title: "데이트 폭력 언론보도의 프레이밍 특성에 대한 연구",
        authors: "Ma, H. H., Shin, J. W., Joo, D. H., Mang, S. W., & Lee, B.",
        date: "2018. 12. 7.",
        conference: "Korea Health Communication Association (KHCA)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/001-image.png",
        pptLink: "assets/presentations/slides/001-slides.pdf",
        sessionPdf: "assets/presentations/sessions/001-session.pdf",
        tags: ["Journalism", "Content analysis", "Media coverage"]
    }
];
