const presentationData = [
    {
        id: "008",
        emoji: "🪴",
        title: "A Preliminary Study for Developing Perceived ESG Scale to Measure Public Perception Toward Organizations’ ESG Performance",
        authors: "Oh, H. J., Park, S. J., Ma, H. H., Lee, B., & Jang, D. Y.",
        date: "2023. 5. 25.",
        conference: "ICA-KACA research session",
        location: "Toronto, Canada",
        image: "assets/presentations/images/008-image.png",
        pptLink: "assets/presentations/slides/008-slides.pdf",
        sessionPdf: "assets/presentations/sessions/008-session.pdf",
        tags: ["Scale development", "Sustainability"],
        award: "Top Paper Award, International Communication Association (ICA), Korean American Communication Association (KACA) Research Session"
    },
    {
        id: "007",
        emoji: "🗣️",
        title: "The Impact of Nonverbal Communication Cues of Avatars on Self-Disclosurein an Immersive Social VR: Focusing on Inter-Avatar Distance and Physical Attractiveness of the Interlocutor’s Avatar",
        authors: "Ma, H. H., Keum, S. Y., Pang, S., Oh, J. H., Lee, J., & Lee, B.",
        date: "2023. 5. 19.",
        conference: "Korean Society For Journalism And Communication Studies (KSJCS)",
        location: "Jeju, Korea",
        image: "assets/presentations/images/007-image.png",
        pptLink: "assets/presentations/slides/007-slides.pdf",
        sessionPdf: "assets/presentations/sessions/007-session.pdf",
        tags: ["Virtual reality", "Social interaction", "Experiment"]
    },
    {
        id: "006",
        emoji: "🗣️",
        title: "Inter-Avatar Distance and Conversation Satisfaction in Immersive VR: Exploring the Moderating Effects of the Sense of Embodiment",
        authors: "Pang, S., Ma, H. H., & Lee, B.",
        date: "2023. 5. 12.",
        conference: "Journal of Cybercommunication Academic Society (JCAS)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/006-image.png",
        pptLink: "assets/presentations/slides/006-slides.pdf",
        sessionPdf: "assets/presentations/sessions/006-session.jpg",
        tags: ["Virtual reality", "Social interaction", "Experiment"]
    },
    {
        id: "005",
        emoji: "🪴",
        title: "조직의 ESG 활동에 대한 공중 인식 평가를 위한 소셜데이터 기반 Perceived ESG Index 개발",
        authors: "Lee, B., Park, S. J., Oh, H. J., Jang, D. Y., Ma, H. H., & Cho, J. H.",
        date: "2022. 11. 25.",
        conference: "Korean Academic Society For Public Relations (KASPR)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/005-image.png",
        pptLink: "assets/presentations/slides/005-slides.pdf",
        sessionPdf: "assets/presentations/sessions/005-session.pdf",
        tags: ["Scale development", "Sustainability"]
    },
    {
        id: "004",
        emoji: "📺",
        title: "Causal impact of television anti-smoking campaign on tobacco sales in Korea: An application of bayesian structural time-series models",
        authors: "Ma, H. H. & Lee, B.",
        date: "2021. 11. 19.",
        conference: "Korea Health Communication Association (KHCA)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/004-image.png",
        pptLink: "assets/presentations/slides/004-slides.pdf",
        sessionPdf: "assets/presentations/sessions/004-session.jpg",
        tags: ["Causal inference", "Bayesian", "Campaign evaluation", "Health communication"]
    },
    {
        id: "003",
        emoji: "📈",
        title: "헬스커뮤니케이션 캠페인의 인과효과 추정",
        authors: "Ma, H. H. & Lee, B.",
        date: "2021. 11. 19.",
        conference: "Korea Health Communication Association (KHCA)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/003-image.png",
        pptLink: "assets/presentations/slides/003-slides.pdf",
        sessionPdf: "assets/presentations/sessions/003-session.jpg",
        tags: ["Causal inference", "Public communication", "Campaign evaluation", "Health communication"]
    },
    {
        id: "002",
        emoji: "📈",
        title: "정부광고 인과 효과 평가 모델에 대한 탐색",
        authors: "Ma, H. H. & Lee, B.",
        date: "2021. 6. 11.",
        conference: "Korea Health Communication Association (KHCA)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/002-image.png",
        pptLink: "assets/presentations/slides/002-slides.pdf",
        sessionPdf: "assets/presentations/sessions/002-session.jpg",
        tags: ["Causal inference", "Public communication", "Campaign evaluation"]
    },
    {
        id: "001",
        emoji: "📰",
        title: "데이트 폭력 언론보도의 프레이밍 특성에 대한 연구",
        authors: "Ma, H. H., Shin, J. W., Joo, D. H., Mang, S. W., & Lee, B.",
        date: "2018. 12. 7.",
        conference: "Korea Health Communication Association (KHCA)",
        location: "Seoul, Korea",
        image: "assets/presentations/images/001-image.png",
        pptLink: "assets/presentations/slides/001-slides.pdf",
        sessionPdf: "assets/presentations/sessions/001-session.pdf",
        tags: ["Journalism", "Content analysis", "Media coverage"]
    }
];
